target:
  column: "suicide" 

date_columns: 
  - iyear

numerical_columns:
  - nperps
  - nperpcap
  - nkill
  - nkillus
  - nkillter
  - nwound
  - nwoundus
  - woundte
  - nhostkid
  - nhostkidus

numeric_categorical_columns: 
  - attacktype1
  
columns_to_exclude: 
  - nhours
  - ransomamt 
  - ransomamtus
  - ransompaid
  - ransompaidus
  - nreleased
  - propvalue
  - extended
  - attacktype2
  - attacktype3
  - weaptype1
  - weaptype2
  - weaptype3
  - weaptype4
  - weapsubtype1
  - weapsubtype2
  - weapsubtype3
  - weapsubtype4 
  - success
  - claimed
  - claimmode
  - claim2
  - claimmode2
  - claim3
  - claimmode3
  - compclaim
  - property
  - propextent
  - ishostkid
  - ransom
  - targtype1
  - targsubtype1
  - targtype2
  - targsubtype2 
  - targtype3
  - targsubtype3
  - hostkidoutcome
  - multiple
  - crit1
  - crit2
  - crit3
  - vicinity
  - individual
  - specificity
  - country
  - region
  - natlty1
  - natlty2
  - natlty3
  - guncertain1
  - guncertain2
  - guncertain3
  - INT_LOG
  - INT_IDEO
  - INT_MISC
  - INT_ANY
  - eventid
  - attacktype1_txt
  - attacktype2_txt
  - attacktype3_txt
  - weaptype1_txt
  - weaptype2_txt
  - weaptype3_txt
  - weaptype4_txt
  - weapsubtype1_txt
  - weapsubtype2_txt
  - weapsubtype3_txt
  - weapsubtype4_txt
  - natlty1_txt
  - natlty2_txt
  - natlty3_txt
  - alternative_txt
  - country_txt
  - targtype1_txt
  - targsubtype1_txt
  - targtype2_txt
  - targsubtype2_txt
  - targtype3_txt
  - targsubtype3_txt
  - propextent_txt
  - hostkidoutcome_txt
  - claimmode_txt
  - claimmode2_txt
  - claimmode3_txt
  - approxdate
  - resolution
  - summary
  - alternative
  - related
  - provstate
  - city
  - location
  - weapdetail
  - corp1
  - corp2
  - corp3
  - target1
  - target2
  - target3
  - gname
  - gsubname
  - gname2
  - gsubname2
  - gname3
  - gsubname3
  - motive
  - propcomment
  - divert
  - kidhijcountry
  - ransomnote
  - addnote
  - scite1
  - scite2
  - scite3
  - dbsource
  - latitude
  - longitude
  - region_txt
  - addnotes
  - imonth
  - iday 
  
missing_value_codes:
  "4":
    - propextent
  "7":
    - hostkidoutcome
  "-9":
    - doubtterr
    - claimed
    - compclaim
    - compclaim2
    - compclaim3
    - property
    - ishostkid
    - ransom
    - INT_LOG
    - INT_IDEO
    - INT_MISC
    - INT_ANY
  "10":
    - claimmode
  "-99":
    - nperps
    - nperpcap
    - nhostkid
    - nhostkidus
    - nhours
    - ndays
    - nreleased
    - propvalue